### ISSUE TITLE
Minor (?) issues with template

### ISSUE THREAD

**Issue by docent** [artemyarulin/om-next-cross-platform-template#1]
Hi Artem, I was playing with your om-next-cross-platform-template and noticed couple of issues:
1. Seems that initial default version number is missing when you generate the project (makes lein fail when it tries to load project.clj), i.e. `(defproject hello-next ...)` instead of `(defproject hello-next "0.0.1-SNAPSHOT" ...)`
2. When I run lein repl I'm getting `java.io.FileNotFoundException: src/app (No such file or directory)` - for some reason in generated project.clj the source path in dev profile is set to `src/app` (I gather it should be src? but not sure)
3. Fixing the previous issue, I think there is still some problem regarding paths of generated `main.js` - it is generated under `resources/public` while the index.html file includes `js/main.js`
4. The `main.js` file writes a script that includes `resources/public/js/goog/base.js` which seems to be wrong with relation to the figwheel server root

Could you please take a look?

**Comment by artemyarulin** [comment]
Hi!

1-4 Damn, I fixed all of those on my machine but forgot to commit - I'm really sorry. I'm planning to make an alpha release of this project on this holidays. Currently I'm fighting with Android version and creating new functionality which allows to sync the state between the devices in real time.

I'll re-check everything and let you know when it's done. Happy New Year!

**Comment by docent** [comment]
That's great to hear :) I'm especially keen on the Android work you mentioned, since I'm planning on Android development myself. Thanks for all the work, it's very useful.

Happy new year to you, too!

**Comment by artemyarulin** [comment]
I fixed all the issues that you mentioned but still battle testings it - I'll notice couple of issues already, will let you know about the progress

**Comment by artemyarulin** [comment]
@docent you may try again to use this template. I've added more instructions about Android development to the readme. It's a bit of hassle right now, but it should take just a couple of minutes to configure it. Feel free to ping me if something does't work or not comfortable enough

**Comment by docent** [comment]
Thanks for the fixes! I will try the template tomorrow and let you know!
