### ISSUE TITLE
Missing cross-platform development link

### ISSUE THREAD

**Issue by orlin** [artemyarulin/om-next-cross-platform-template#6]
The "more info" link points to an issue of a repo that no longer exists - [kapteko](https://github.com/kapteko) has no public repos atm...

**Comment by artemyarulin** [comment]
Thank you! Unfortunately I've removed the repo and it doesn't have an issue description anymore, sorry for that. But to be honest ReactNative changes so fast there is a big chance that information there is outdated. 

In general you just have to change output js file name somewhere in configuration for Android project and point it to the ios version js file

**Comment by orlin** [comment]
Thanks, I didn't realise that was your org.

So, the same js file is used for both iOS and Android?  Would that be because Android is more flexible with the filename it loads, or could it go either way -- i.e. iOS configured to load Android's js (just as well)?  I renamed it already and I'd rather have android lead the way unless I run into issues...

**Comment by artemyarulin** [comment]
You are right - last time when I was trying to unify and use the same file name I had some difficulties with iOS version (don't remember but I assume it was hardcoded somewhere). But in the end - it's not that big of an issue, it's just a filename 

P.S. Reminder for myself - never delete projects in Github as some other project may refer to that
